//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        [Display (Name = "Appointment No.")]
        public int idAppointment { get; set; }
        public string patientID { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        [Display(Name = "Reason for Missing")]
        public string reason_for_missing_appointment { get; set; }
        [Display (Name = "Visit No.")]
        public int Visit_idVisit { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
