//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int idAppointment { get; set; }
        public string patientID { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string reason_for_missing_appointment { get; set; }
        public int Visit_idVisit { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
