//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow_up
    {
        public int idFollow_up { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> follow_up_date { get; set; }
        public Nullable<System.TimeSpan> Follow_up_time { get; set; }
        public int Visit_idVisit { get; set; }
    
        public virtual Visit Visit { get; set; }
    }
}
