//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int idFamily_history { get; set; }
        public string Patient_idPatient { get; set; }
        public Nullable<int> hist_type { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
