//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOSPITALEntities : DbContext
    {
        public HOSPITALEntities()
            : base("name=HOSPITALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Bed> Beds { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Diagnosi> Diagnosis { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Follow_up> Follow_up { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Lab_header> Lab_header { get; set; }
        public virtual DbSet<Lab_test_lines> Lab_test_lines { get; set; }
        public virtual DbSet<Lab_test_results> Lab_test_results { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Pharmacy> Pharmacies { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Radio_Image> Radio_Image { get; set; }
        public virtual DbSet<Sales_header> Sales_header { get; set; }
        public virtual DbSet<Sales_line> Sales_line { get; set; }
        public virtual DbSet<Triage> Triages { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
