//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lab_header()
        {
            this.Lab_test_results = new HashSet<Lab_test_results>();
        }
    
        public int idLab_header { get; set; }
        public string userID { get; set; }
        public Nullable<int> visitID { get; set; }
        public Nullable<System.DateTime> lab_test_date { get; set; }
        public Nullable<System.TimeSpan> lab_test_time { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab_test_results> Lab_test_results { get; set; }
    }
}
