//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Radio_Image
    {
        public int idRadio_Image { get; set; }
        [Display(Name = "VisitID")]
        public Nullable<int> visitID { get; set; }
        [Display(Name = "Observation")]
        public string imageObservation { get; set; }
        [Display(Name = "UserID")]
        public string userID { get; set; }
        [Display(Name = "Time")]
        public Nullable<System.DateTime> image_date { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual User User { get; set; }
    }
}
