//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visit()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Follow_up = new HashSet<Follow_up>();
            this.Lab_header = new HashSet<Lab_header>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Radio_Image = new HashSet<Radio_Image>();
            this.Triages = new HashSet<Triage>();
            this.Diagnosis = new HashSet<Diagnosi>();
            this.Doctors = new HashSet<Doctor>();
            this.Operations = new HashSet<Operation>();
        }
        [Display(Name = "Visit No.")]
        public int idVisit { get; set; }
        [Display(Name = "PatientID")]
        public string patientID { get; set; }
        [Display(Name = "Date")]
        public Nullable<System.DateTime> visit_date { get; set; }
        [Display(Name = "DoctorID")]
        public string doctorID { get; set; }
        [Display(Name = "Procedure")]
        public Nullable<int> procedureID { get; set; }
        [Display(Name = "Type")]
        public Nullable<int> visit_type { get; set; }
        [Display(Name = "Time")]
        public Nullable<System.TimeSpan> time { get; set; }
        [Display(Name = "Bed No.")]
        public int Bed_idBed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Bed Bed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow_up> Follow_up { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab_header> Lab_header { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Radio_Image> Radio_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Triage> Triages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosi> Diagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operations { get; set; }
    }
}
